### ISSUE TITLE
Sonatype reported problems on accessing to the chat

### ISSUE THREAD

**Issue by lvca** [orientechnologies/prjhub#27]
This is the output in browser console. I have the same but works. @maggiolo00 could you understand and fix this problem, please?

https://www.evernote.com/shard/s18/sh/2b4a44cf-9f7d-419a-8eaf-4d693bef8941/53db19e0f356a65e5eab8af9ea622234

**Comment by lvca** [comment]
Problem fixed weeks ago. The JS error doesn't cause problems, but it would be nice to don't see it.

**Comment by wolf4ood** [comment]
Closing this since has been resolved
