### ISSUE TITLE
How do I find closed bugs that I enterd in prjhub?

### ISSUE THREAD

**Issue by nmcintyre2014** [orientechnologies/prjhub#69]
Is there a search I can run to find all the bugs that I opened that are closed?

**Comment by lvca** [comment]
What do you see on the PrjHub home?

**Comment by nmcintyre2014** [comment]
I only see open bugs on the home page.  I got a url from Ori that can get me all of DigitalGlobe's bugs.  Is there any documentation on what fields I can query on?

**Comment by wolf4ood** [comment]
Implemented in Home Page Opened/Closed
