### ISSUE TITLE
New button "It's a question"

### ISSUE THREAD

**Issue by lvca** [orientechnologies/prjhub#71]
This button should:
- auto assign the label "Question"
- Comment the issue with this exact message: "This is a question, but we rather use the Issue Tracker to track enhancements and bugs. The best place to ask for questions about OrientDB is the Open Community Group: https://groups.google.com/forum/#!forum/orient-database. Please could you create a new topic with your question on it? Thanks."
- Auto close the issue

**Comment by wolf4ood** [comment]
Implemented
