### ISSUE TITLE
"Connection lost" when switching between chat rooms

### ISSUE THREAD

**Issue by luigidellaquila** [orientechnologies/prjhub#86]
When switching between chat rooms a message appears in the top of the window saying "Connection lost. Reconnecting now."

It blocks the screen and a page refresh is needed to continue

**Comment by andrii0lomakin** [comment]
+1

On Thu, Dec 10, 2015, 17:51 luigidellaquila notifications@github.com
wrote:

> When switching between chat rooms a message appears in the top of the
> window saying "Connection lost. Reconnecting now."
> 
> It blocks the screen and a page refresh is needed to continue
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/orientechnologies/prjhub/issues/86.
> 
> ## 
> 
> Best regards,
> Andrey Lomakin, R&D lead.
> OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin
