### ISSUE TITLE
NCS - Unable to failover in orientdb replication databases

### ISSUE THREAD

**Issue by yeoce** [orientechnologies/prjhub#99]
Hi Luigi,

We encountered our application not able to failover from dbnode1(Master) to dbnode2(Slave) (which both have been setup in replicated mode).  Our application connection string looks like this:
remote:172.25.0.5/isc;remote:172.25.0.6/isc

172.25.0.5 is dbnode01 which we shut it down.  our application experienced OStorageException: Cannot open a connection to remote server: 172.25.0.5:2424/isc.

environment: Centos 7
version: 2.2.0 beta2

**Comment by lvca** [comment]
Hi @yeoce, I suggest you to upgrade (doesn't require to recompile, just update the libraries) to the last hotfix 2.2.7 that contains some bug fixed on that. Once upgraded please try to kill the servers and check if clients are able to reconnect.

**Comment by lvca** [comment]
Closing because no answer after a while. In case please reopen/comment this.
